name: Farmer Dev Deployment

on:
  push:
 
    paths: 
      - "Applications/farmer"
      - "!Applications/marketplace"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm ui build

      - name: Create release
        uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.GREENSYNC_TOKEN }}
          release-type: node
          package-name: farmer-dashboard
          bump-minor-pre-major: true

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GREENSYNC_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGRPRJ }}'
          channelId: live
          projectId: agrprj
          site: farmerdash-dev