name: Farmer Dev Deployment

on:
  push:
    branches:
      - "feature/mitch"
      - "feature/staged-changes"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 16 ]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: build application
        run: pnpm ui build && pnpm client build
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.GREENSYNC_TOKEN }}
          release-type: node
          package-name: farmer-dashboard
          bump-minor-pre-major: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GREENSYNC_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGRPRJ }}'
          channelId: live
          projectId: agrprj
          target: farmerdash-dev
          entryPoint: 'Applications/farmer'