name: Farmer Production Deployment

on:
  pull_request:
    types:
      - "closed"
    paths: 
      - "Applications/farmer/*"
      - "!Applications/marketplace"
env:
  VITE_REACT_FIREBASE_API_KEY: ${{secrets.VITE_REACT_FIREBASE_API_KEY}}
  VITE_REACT_FIREBASE_AUTH_DOMAIN: agrprj.firebaseapp.com
  VITE_REACT_FIREBASE_PROJECT_ID: agrprj
  VITE_REACT_FIREBASE_STORAGE_BUCKET: agrprj.appspot.com
  VITE_REACT_FIREBASE_MESSEGING_SENDER_ID: 1006449928819
  VITE_REACT_FIREBASE_APP_ID: 1:1006449928819:web:1e0cee2dabf347db19d806
  VITE_REACT_GRAPHQL_URL: https://api.greensync.co.za/v1/graphql


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm ui build

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: Applications/farmer/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: Applications/farmer/dist

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GREENSYNC_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGRPRJ }}'
          channelId: live
          projectId: agrprj
          site: farmerdash

  create_and_merge_pr:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated PR
          title: Automated PR
          body: Automated PR created by scheduled job
          branch: feature/frontend
          base: main

      - name: Merge pull request
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-number: ${{ steps.create_pull_request.outputs.pull_number }}
          merge-method: squash

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGRPRJ }}'
          channelId: live
          projectId: agrprj
          site: farmerdash